import { buttonVariants } from "@/components/ui/button"
import "./globals.css"
import { Providers } from "./providers"
import { cn } from "@/lib/utils"
import Link from "next/link"
import { MainNav } from "./components/MainNav/MainNav"
import { marketingConfig } from "@/config/marketing"
import { SiteFooter } from "./components/SiteFooter/SiteFooter"
import { UserAccountNav } from "./components/UserAccountNav/UserAccountNav"
import { getCurrentUser } from "@/lib/session"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await getCurrentUser()

  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen flex-col">
          <header className="container z-40 bg-background">
            <div className="flex h-20 items-center justify-between py-6">
              <MainNav items={marketingConfig.mainNav} />
              {!user ? (
                <nav>
                  <Link
                    href="/login"
                    className={cn(
                      buttonVariants({ variant: "secondary", size: "sm" }),
                      "px-4"
                    )}
                  >
                    Login
                  </Link>
                </nav>
              ) : (
                <UserAccountNav
                  user={{
                    name: user?.name,
                    image: user?.image,
                    email: user?.email,
                    //@ts-ignore
                    role: user?.role,
                  }}
                />
              )}
            </div>
          </header>
          <Providers>{children}</Providers>
          <SiteFooter />
        </div>
      </body>
    </html>
  )
}
